import { StyleSheet } from 'react-native';

export const COLORS = {
  bg: '#ffffff',
  ink: '#111111',
  muted: '#888888',
  line: '#ececec',
  soft: '#fafafa',
  warn: '#b25400',
  ok: '#1a7a3a',
};

export const S = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg },
  topbar: {
    height: 56,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.bg,
  },
  topbarTitle: { fontSize: 18, fontWeight: '600', color: COLORS.ink },
  topbarDate: { fontSize: 13, color: COLORS.muted },
  tabs: {
    flexDirection: 'row',
    height: 64,
    borderTopWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.bg,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabText: { fontSize: 13, color: COLORS.muted },
  tabTextActive: { color: COLORS.ink, fontWeight: '600' },
  scroll: { padding: 16, paddingBottom: 24 },
  sectionTitle: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    color: COLORS.muted,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 8,
  },
  card: {
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 8,
  },
  timelineRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    gap: 14,
  },
  timelineRowLast: { borderBottomWidth: 0 },
  timelineTime: { width: 52, fontSize: 13, color: COLORS.muted, fontVariant: ['tabular-nums'] },
  timelineText: { flex: 1, fontSize: 15, color: COLORS.ink },
  exoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    gap: 12,
  },
  exoRowLast: { borderBottomWidth: 0 },
  // Colonne fixe pour aligner le texte après la vignette (peu importe sa largeur)
  exoThumbCol: {
    width: 88, height: 56,
    alignItems: 'center', justifyContent: 'center',
  },
  exoThumb: {
    height: 56, borderRadius: 8,
    backgroundColor: COLORS.soft,
    borderWidth: 1, borderColor: COLORS.line,
    overflow: 'hidden',
  },
  exoInfo: { flex: 1 },
  exoName: { fontSize: 15, fontWeight: '500', color: COLORS.ink, marginBottom: 2 },
  exoMeta: { fontSize: 13, color: COLORS.muted },
  exoWarn: { fontSize: 12, color: COLORS.warn, marginTop: 2 },
  exoLast: { fontSize: 12, color: COLORS.ok, marginTop: 2 },
  chevron: { fontSize: 22, color: COLORS.muted, marginLeft: 4 },
  detailImg: {
    width: '100%',
    height: 220,
    backgroundColor: COLORS.soft,
    borderRadius: 12,
    borderWidth: 1, borderColor: COLORS.line,
    marginBottom: 16,
    alignItems: 'center', justifyContent: 'center',
    overflow: 'hidden',
  },
  detailName: { fontSize: 22, fontWeight: '600', color: COLORS.ink, marginBottom: 4 },
  detailMeta: { fontSize: 14, color: COLORS.muted, marginBottom: 4 },
  detailWarn: {
    backgroundColor: '#fff7eb',
    borderWidth: 1, borderColor: '#f3d6a5',
    padding: 10, borderRadius: 8,
    fontSize: 13, color: COLORS.warn,
    marginTop: 10, marginBottom: 12,
  },
  setRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  setLabel: { width: 60, fontSize: 14, color: COLORS.muted },
  setInput: {
    flex: 1, fontSize: 16, paddingHorizontal: 12, paddingVertical: 12,
    borderWidth: 1, borderColor: COLORS.line, borderRadius: 8,
    backgroundColor: COLORS.soft, color: COLORS.ink,
  },
  notes: {
    fontSize: 14, padding: 12, borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 8, backgroundColor: COLORS.soft, color: COLORS.ink,
    minHeight: 80, marginTop: 8, textAlignVertical: 'top',
  },
  saveBtn: {
    backgroundColor: COLORS.ink, paddingVertical: 16, borderRadius: 10,
    alignItems: 'center', marginTop: 16,
  },
  saveBtnText: { color: COLORS.bg, fontSize: 16, fontWeight: '600' },
  backBtn: {
    paddingVertical: 8, paddingHorizontal: 12,
    borderWidth: 1, borderColor: COLORS.line, borderRadius: 8,
    alignSelf: 'flex-start', marginBottom: 12,
  },
  backBtnText: { fontSize: 14, color: COLORS.ink },
  historyRow: { paddingVertical: 12, borderBottomWidth: 1, borderColor: COLORS.line },
  historyDate: { fontSize: 13, color: COLORS.muted, marginBottom: 4 },
  historySession: { fontSize: 15, fontWeight: '500', color: COLORS.ink, marginBottom: 4 },
  historyExos: { fontSize: 13, color: COLORS.muted },
  historyNotes: {
    fontSize: 13, color: COLORS.ink, marginTop: 6,
    paddingHorizontal: 10, paddingVertical: 8, backgroundColor: COLORS.soft,
    borderRadius: 6, fontStyle: 'italic',
  },
  empty: { textAlign: 'center', color: COLORS.muted, padding: 40, fontSize: 14 },

  // === Picker Entraînement ===
  pickerCard: {
    backgroundColor: COLORS.bg,
    borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 12,
    padding: 18,
    marginBottom: 12,
  },
  pickerDay: { fontSize: 12, color: COLORS.muted, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '600' },
  pickerTitle: { fontSize: 20, fontWeight: '600', color: COLORS.ink, marginTop: 2, marginBottom: 8 },
  pickerExos: { fontSize: 13, color: COLORS.muted, lineHeight: 19 },
  pickerCta: { fontSize: 13, fontWeight: '600', color: COLORS.ink, marginTop: 12 },
  pickerInProgress: {
    backgroundColor: '#fff7eb',
    borderColor: '#f3d6a5',
  },
  pickerBadge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.warn,
    color: COLORS.bg,
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8, paddingVertical: 3,
    borderRadius: 4,
    marginBottom: 8,
    overflow: 'hidden',
  },

  // === Session Log ===
  logHeader: {
    paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12,
    borderBottomWidth: 1, borderColor: COLORS.line,
  },
  logTitle: { fontSize: 22, fontWeight: '700', color: COLORS.ink },
  logProgress: { fontSize: 13, color: COLORS.muted, marginTop: 4 },

  logExoBlock: {
    backgroundColor: COLORS.bg,
    borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  logExoHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 },
  logExoName: { fontSize: 15, fontWeight: '600', color: COLORS.ink, flex: 1 },
  logExoMeta: { fontSize: 12, color: COLORS.muted, marginBottom: 8 },
  logExoWarn: { fontSize: 12, color: COLORS.warn, marginBottom: 8 },

  logSetsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  logSetCell: { width: 70 },
  logSetLabel: { fontSize: 11, color: COLORS.muted, marginBottom: 2, textAlign: 'center' },
  logSetInput: {
    fontSize: 16,
    paddingVertical: 10, paddingHorizontal: 6,
    borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 8,
    backgroundColor: COLORS.soft,
    color: COLORS.ink,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  logSetInputFilled: {
    backgroundColor: '#f0f7f2',
    borderColor: '#c8e2cf',
    color: COLORS.ok,
  },
  logExoNote: {
    fontSize: 13,
    padding: 10, marginTop: 10,
    borderWidth: 1, borderColor: COLORS.line, borderRadius: 8,
    backgroundColor: COLORS.soft,
    color: COLORS.ink,
    minHeight: 38,
    textAlignVertical: 'top',
  },
  cardioBadge: { fontSize: 12, color: COLORS.muted, fontStyle: 'italic', marginTop: 4 },

  logFooter: {
    borderTopWidth: 1, borderColor: COLORS.line,
    backgroundColor: COLORS.bg,
    padding: 12,
  },
  logFinishBtn: {
    backgroundColor: COLORS.ink,
    paddingVertical: 16, borderRadius: 10,
    alignItems: 'center',
  },
  logFinishBtnText: { color: COLORS.bg, fontSize: 16, fontWeight: '700' },
  logCancelBtn: { padding: 12, alignItems: 'center' },
  logCancelBtnText: { color: COLORS.muted, fontSize: 14 },

  // === Marche ===
  walkHero: {
    backgroundColor: COLORS.ink,
    borderRadius: 12,
    padding: 18,
    marginBottom: 12,
  },
  walkHeroDay: { color: '#aaa', fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '600' },
  walkHeroDuration: { color: COLORS.bg, fontSize: 36, fontWeight: '700', marginVertical: 4, fontVariant: ['tabular-nums'] },
  walkHeroSpot: { color: COLORS.bg, fontSize: 15, fontWeight: '500' },
  walkHeroIntensity: { color: '#bbb', fontSize: 13, marginTop: 2 },
  walkHeroNote: { color: '#ffcc4d', fontSize: 13, marginTop: 10 },
  walkHeroVest: { color: '#ffcc4d', fontSize: 13, marginTop: 4 },
  walkHeroBtn: {
    backgroundColor: COLORS.bg,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 14,
    alignItems: 'center',
  },
  walkHeroBtnText: { color: COLORS.ink, fontWeight: '700', fontSize: 14 },
  walkHeroBtnDone: { backgroundColor: '#2a3d2f' },
  walkHeroBtnDoneText: { color: '#c8e2cf' },

  weekBar: {
    height: 8,
    backgroundColor: COLORS.line,
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: 8,
  },
  weekBarFill: { height: '100%', backgroundColor: COLORS.ink },

  dayRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    alignItems: 'center',
    gap: 12,
  },
  dayRowToday: { backgroundColor: '#fafafa', marginHorizontal: -16, paddingHorizontal: 16 },
  dayName: { width: 60, fontSize: 14, fontWeight: '500', color: COLORS.ink },
  dayTarget: { flex: 1, fontSize: 13, color: COLORS.muted, fontVariant: ['tabular-nums'] },
  dayDone: { fontSize: 13, color: COLORS.ok, fontWeight: '600', fontVariant: ['tabular-nums'] },
  dayMissed: { fontSize: 13, color: COLORS.muted, fontStyle: 'italic' },

  weightCard: {
    backgroundColor: COLORS.bg,
    borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
  },
  weightLine: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  weightCurrent: { fontSize: 28, fontWeight: '700', color: COLORS.ink, fontVariant: ['tabular-nums'] },
  weightTarget: { fontSize: 13, color: COLORS.muted },
  weightDelta: { fontSize: 13, color: COLORS.ok, fontWeight: '600', marginTop: 4 },

  // === Export / Import bar (discret en bas d'Historique) ===
  ioBar: {
    flexDirection: 'row', justifyContent: 'center', gap: 20,
    paddingVertical: 16,
  },
  ioBtn: { paddingVertical: 6, paddingHorizontal: 10 },
  ioBtnText: { fontSize: 12, color: COLORS.muted, textDecorationLine: 'underline' },

  // === Lightbox ===
  lightboxOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center', justifyContent: 'center',
    padding: 20,
    zIndex: 2000,
  },
  lightboxClose: {
    position: 'absolute', top: 50, right: 20,
    width: 44, height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center', justifyContent: 'center',
    zIndex: 1,
  },
  lightboxCloseText: { color: '#fff', fontSize: 22, fontWeight: '300' },
  lightboxCaption: {
    position: 'absolute', bottom: 40, left: 20, right: 20,
    color: '#fff', textAlign: 'center',
    fontSize: 15, fontWeight: '500',
  },

  // === Modale confirm ===
  modalOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center', justifyContent: 'center',
    padding: 24, zIndex: 1000,
  },
  modalCard: {
    backgroundColor: COLORS.bg,
    borderRadius: 14,
    padding: 24,
    width: '100%', maxWidth: 360,
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: COLORS.ink, marginBottom: 8 },
  modalText: { fontSize: 14, color: COLORS.muted, marginBottom: 18, lineHeight: 20 },
  modalBtns: { flexDirection: 'row', gap: 8 },
  modalBtnGhost: {
    flex: 1, paddingVertical: 12, borderRadius: 8,
    borderWidth: 1, borderColor: COLORS.line,
    alignItems: 'center',
  },
  modalBtnGhostText: { color: COLORS.ink, fontWeight: '600' },
  modalBtnPrimary: {
    flex: 1, paddingVertical: 12, borderRadius: 8,
    backgroundColor: COLORS.ink,
    alignItems: 'center',
  },
  modalBtnPrimaryText: { color: COLORS.bg, fontWeight: '600' },
  toast: {
    position: 'absolute', bottom: 90, alignSelf: 'center',
    backgroundColor: COLORS.ink, paddingHorizontal: 20, paddingVertical: 10,
    borderRadius: 20,
  },
  toastText: { color: COLORS.bg, fontSize: 14 },
});
