import { StyleSheet } from 'react-native';

export const COLORS = {
  bg: '#ffffff',
  ink: '#111111',
  muted: '#888888',
  line: '#ececec',
  soft: '#fafafa',
  warn: '#b25400',
  ok: '#1a7a3a',
};

export const S = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg },
  topbar: {
    height: 56,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.bg,
  },
  topbarTitle: { fontSize: 18, fontWeight: '600', color: COLORS.ink },
  topbarDate: { fontSize: 13, color: COLORS.muted },
  tabs: {
    flexDirection: 'row',
    height: 64,
    borderTopWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.bg,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabText: { fontSize: 13, color: COLORS.muted },
  tabTextActive: { color: COLORS.ink, fontWeight: '600' },
  scroll: { padding: 16, paddingBottom: 24 },
  sectionTitle: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    color: COLORS.muted,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 8,
  },
  card: {
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 8,
  },
  timelineRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    gap: 14,
  },
  timelineRowLast: { borderBottomWidth: 0 },
  timelineTime: { width: 52, fontSize: 13, color: COLORS.muted, fontVariant: ['tabular-nums'] },
  timelineText: { flex: 1, fontSize: 15, color: COLORS.ink },
  exoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: COLORS.line,
    gap: 12,
  },
  exoRowLast: { borderBottomWidth: 0 },
  exoThumb: {
    width: 56, height: 56, borderRadius: 8,
    backgroundColor: COLORS.soft,
    borderWidth: 1, borderColor: COLORS.line,
    alignItems: 'center', justifyContent: 'center',
    overflow: 'hidden',
  },
  exoInfo: { flex: 1 },
  exoName: { fontSize: 15, fontWeight: '500', color: COLORS.ink, marginBottom: 2 },
  exoMeta: { fontSize: 13, color: COLORS.muted },
  exoWarn: { fontSize: 12, color: COLORS.warn, marginTop: 2 },
  exoLast: { fontSize: 12, color: COLORS.ok, marginTop: 2 },
  chevron: { fontSize: 22, color: COLORS.muted, marginLeft: 4 },
  detailImg: {
    width: '100%',
    height: 220,
    backgroundColor: COLORS.soft,
    borderRadius: 12,
    borderWidth: 1, borderColor: COLORS.line,
    marginBottom: 16,
    alignItems: 'center', justifyContent: 'center',
    overflow: 'hidden',
  },
  detailName: { fontSize: 22, fontWeight: '600', color: COLORS.ink, marginBottom: 4 },
  detailMeta: { fontSize: 14, color: COLORS.muted, marginBottom: 4 },
  detailWarn: {
    backgroundColor: '#fff7eb',
    borderWidth: 1, borderColor: '#f3d6a5',
    padding: 10, borderRadius: 8,
    fontSize: 13, color: COLORS.warn,
    marginTop: 10, marginBottom: 12,
  },
  setRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  setLabel: { width: 60, fontSize: 14, color: COLORS.muted },
  setInput: {
    flex: 1, fontSize: 16, paddingHorizontal: 12, paddingVertical: 12,
    borderWidth: 1, borderColor: COLORS.line, borderRadius: 8,
    backgroundColor: COLORS.soft, color: COLORS.ink,
  },
  notes: {
    fontSize: 14, padding: 12, borderWidth: 1, borderColor: COLORS.line,
    borderRadius: 8, backgroundColor: COLORS.soft, color: COLORS.ink,
    minHeight: 80, marginTop: 8, textAlignVertical: 'top',
  },
  saveBtn: {
    backgroundColor: COLORS.ink, paddingVertical: 16, borderRadius: 10,
    alignItems: 'center', marginTop: 16,
  },
  saveBtnText: { color: COLORS.bg, fontSize: 16, fontWeight: '600' },
  backBtn: {
    paddingVertical: 8, paddingHorizontal: 12,
    borderWidth: 1, borderColor: COLORS.line, borderRadius: 8,
    alignSelf: 'flex-start', marginBottom: 12,
  },
  backBtnText: { fontSize: 14, color: COLORS.ink },
  historyRow: { paddingVertical: 12, borderBottomWidth: 1, borderColor: COLORS.line },
  historyDate: { fontSize: 13, color: COLORS.muted, marginBottom: 4 },
  historySession: { fontSize: 15, fontWeight: '500', color: COLORS.ink, marginBottom: 4 },
  historyExos: { fontSize: 13, color: COLORS.muted },
  historyNotes: {
    fontSize: 13, color: COLORS.ink, marginTop: 6,
    paddingHorizontal: 10, paddingVertical: 8, backgroundColor: COLORS.soft,
    borderRadius: 6, fontStyle: 'italic',
  },
  empty: { textAlign: 'center', color: COLORS.muted, padding: 40, fontSize: 14 },
  toast: {
    position: 'absolute', bottom: 90, alignSelf: 'center',
    backgroundColor: COLORS.ink, paddingHorizontal: 20, paddingVertical: 10,
    borderRadius: 20,
  },
  toastText: { color: COLORS.bg, fontSize: 14 },
});
